### PR TITLE
Update template_smiles.h

### PR DESCRIPTION
**Pull request by ZontaNicola**
CRDGEN-98 CRDGEN-103

### CODE REVIEW

**Comment by ricrogz** [comment]
@ZontaNicola, instead of updating the header directly, would you mind moving your changes to the `templates.smi`, so that the automated checks can run on them?

There's instructions here: https://github.com/rdkit/molecular_templates#how-to-contribute

**Comment by ZontaNicola** [comment]
whoops thanks!

**Comment by cdvonbargen** [comment]
would it be possible to make the coordinates more 3d-like the suggested templates in those cases? my assumption is that we're taking cues from cubane's 3d-like structure? or do we not want that?

Screenshot 2023-11-16 at 1 45 27 PM Screenshot 2023-11-16 at 1 45 09 PM

**Comment by cdvonbargen** [comment]
Weird, it wouldn't let me post two images, here's the other one:

160px-Superphane

**Comment by ZontaNicola** [comment]
Talked this through with @cdvonbargen and got DDAG's approval on the structures I suggested. @rachelnwalker @ricrogz  is there anything else that I need to do here?

**Review by ricrogz — APPROVED** [review]
LGTM

**Comment by ricrogz** [comment]
> Talked this through with @cdvonbargen and got DDAG's approval on the structures I suggested. @rachelnwalker @ricrogz is there anything else that I need to do here?

You are good Nic. I just merged your PR. This will trigger the CI and update the header & stuff in a couple of minutes.

**Comment by rachelnwalker** [comment]
Thank you @ZontaNicola!

**Pull request merged**
