### PR TITLE
Add a workflow that runs some tests and posts template imgs to the PR

### PR DESCRIPTION
**Pull request by ricrogz**
This adds a workflow that checks the CXSMILES templates added to `templates.smi`, runs some checks on them, and then generates some images and posts them to PRs. There's also a README with some instructions.

An example PR https://github.com/ricrogz/molecular_templates/pull/3 with its corresponding Actions run, https://github.com/ricrogz/molecular_templates/actions/runs/5731299131.

Note that the workflow is configure to trigger only when there's a PR (or an update to a PR) that updates `templates.smi`. When this happens, the workflow will trigger, running the tests and posting the images to the PR (note all added/changed templates in the PR branch will be posted each time the branch is updated!).

Regarding the images, Github does not allow posting images from Github Actions runs, so I'm uploading them to imgur, and posting the links to the PR. Setting this up requires some additional configuration on the repo and also on imgur. Specifically:
A new imgur account should be created, and a new application registered under it (https://api.imgur.com/oauth2/addclient). 
Please make sure to write down the "client id" and "client secret". These are required to generate a token following the instructions under `Forming the authorization URL` in https://apidocs.imgur.com. The token should provide the following elements: `access_token`, `refresh_token`, `expires_in`, `token_type`.

With this information, two GitHub Actions Secrets should be created: `IMGUR_CLIENT_ID`, containing the value of `cliend_id`, and another one named `IMGUR_TOKEN`, containing a json object with the 4 elements of the imgur token we created, i.e.:

```python
IMGUR_TOKEN = json.dumps({
    'access_token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'refresh_token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'expires_in': '315360000',
    'token_type': 'bearer',
}
```

Note that the token will expire in 10 years. There's a mechanism to automatically renew it and update the GitHub Secret, but this requires setting up some permissions I'm not very happy to grant, so we'll have to manually renew the token in 10 years (hopefully).

Note that this PR does not generate the actual header file containing the templates. This is because we can't modify the PR from within a workflow run, and, according to what I have read, there isn't an option to trigger Github Actions when a PR is merged. I am planning to set up a separate workflow that, if there are any new templates, updates the header once a day and creates a PR to merge it into RDKit.

### CODE REVIEW

**Comment by ricrogz** [comment]
A couple things I forgot:
- It seems we already have 3 duplicate templates! Check out "Run check for duplicates" in https://github.com/ricrogz/molecular_templates/actions/runs/5731299131/job/15531930695 (I marked the check as xfail so that it doesn't automatically fail the workflow runs) !
- For the Actions to be triggered, they have to be enabled in the repository, of course.

**Comment by ricrogz** [comment]
Sorry, I accidentally renamed the `main` branch on my repo (which closed this PR).

**Comment by d-b-w** [comment]
It would be nice not to upload to imgur, however Ricardo mentioned that he tried:

* Embedding an svg in the description. This is not allowed in markdown, which supports only a limited subset of HTML
* Embedding the image data as a binary blob in the message. It seems like github disallows this.

I think that this approach makes sense! If there are no further comments, I think this should be merged.

**Comment by greglandrum** [comment]
@ricrogz I followed the instructions (hopefully correctly) to setup the secrets for the imgur service on the repo.
I also added you as an admin to the repo. I hope that's enough to get the service connection set up?

**Comment by ricrogz** [comment]
> @ricrogz I followed the instructions (hopefully correctly) to setup the secrets for the imgur service on the repo. I also added you as an admin to the repo. I hope that's enough to get the service connection set up?

Hm, there seems to be something wrong with the IMGUR token, but I'll try to fix it.

**Comment by greglandrum** [comment]
> Hm, there seems to be something wrong with the IMGUR token, but I'll try to fix it.

I wouldn't find that overly surprising.

**Comment by ricrogz** [comment]
Ugh! Of course. It seems that secrets do not get transmitted to Workflow runs triggered by Pull Requests. Or at least when these do not origintate in the same repo?

**Pull request merged**
